name: MultiCurrency
version: '${project.version}'
main: dev.sweplays.multicurrency.MultiCurrency
api-version: 1.19
authors: [ SweplaysYT ]
softdepend:
  - PlaceholderAPI
description: A multi-currency plugin made with love by SweplaysYT
